before_commands:
    - sudo pip3 install cleo
    - sudo pip3 install pystratum-mysql

build:
    dependencies:
        before:
          - pip3 install cleo
          - pip3 install pystratum-mysql

          - wget https://dev.mysql.com/get/Downloads/Connector-Python/mysql-connector-python-2.1.3.tar.gz
          - tar zxvf mysql-connector-python-2.1.3.tar.gz
          - cd mysql-connector-python-2.1.3 && python3 setup.py install

        override:
            -
                command: coverage run -m unittest discover -s test -p *Test.py
                coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
